name: dp_inference
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - clarabel=0.7.1
  - comm=0.2.2
  - contourpy=1.2.0
  - cvxpy=1.4.3
  - cvxpy-base=1.4.3
  - cycler=0.11.0
  - debugpy=1.8.1
  - decorator=5.1.1
  - ecos=2.0.13
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - importlib-metadata=7.1.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=16.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libosqp=0.6.3
  - libpng=1.6.39
  - libqdldl=0.1.7
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mkl=2022.2.1
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.2.1
  - osqp=0.6.3
  - packaging=23.2
  - pandas=2.2.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.1
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - pyparsing=3.0.9
  - python=3.10.14
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyzmq=26.0.0
  - qdldl-python=0.1.7.post1
  - readline=8.2
  - scikit-learn=1.3.0
  - scipy=1.12.0
  - scs=3.2.4.post1
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.14.2
  - typing_extensions=4.11.0
  - tzdata=2024a
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - arrow==1.3.0
      - binaryornot==0.4.4
      - certifi==2024.2.2
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cookiecutter==2.6.0
      - folktables==0.0.12
      - idna==3.7
      - jinja2==3.1.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - python-dateutil==2.9.0.post0
      - python-slugify==8.0.4
      - pyyaml==6.0.1
      - requests==2.31.0
      - rich==13.7.1
      - text-unidecode==1.3
      - types-python-dateutil==2.9.0.20240316
      - urllib3==2.2.1
